### ISSUE TITLE
"Page not found" when user click on "Updated camp Recent Activity"

### ISSUE THREAD

**Issue by hassaanCD** [the-canonizer/canonizer-3.0-api#680]
Steps to Reproduce:

1. Create New Topic
2. Create camp
3. Add support to camp
4. Update the camp
5. It will show in main page "Recent Activity"

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/aabd4d68-e441-4ecb-9603-3cb3e312eb24)

6. Click on "Update Camp" in "Recent Activity" 
7. It will land to "Page not Found" 

![Image](https://github.com/the-canonizer/canonizer-3.0-api/assets/120023458/2bf36b04-dbca-4242-8a70-d81c678ae0ac)

**Comment by sajid315** [comment]
@hassaanCD this issue has been fixed. 
Refer commit: 
https://github.com/the-canonizer/canonizer-3.0-api/commit/537073806a4deaf4136627f6bf3b5336b9f71d4b

**Comment by rupalichavan9860** [comment]
Working fine on staging

**Comment by sajid315** [comment]
@rupalichavan9860 i think this ticket also moved to production now ? not sure.

**Comment by rupalichavan9860** [comment]
@sajid315 I will check and update

**Comment by rupalichavan9860** [comment]
@sajid315 This is working for new activities but still getting "Page not found" on previous "Updated a camp" activity.
Please refer attached screenshot : 
![image](https://github.com/the-canonizer/canonizer-3.0-api/assets/40416610/2b94b38b-de4a-453c-8d33-72e8b5f9d5e5)

**Comment by sajid315** [comment]
@rupalichavan9860 i have fixed the issue for older activities and also deployed on staging on call with Ashutosh. 
So we need to verify all older links then we will resolve the same on production by script.

**Comment by rupalichavan9860** [comment]
@sajid315 I am still facing the same issue for old camps 
reference links :
https://canonizer3.canonizer.com/history/2608/1
https://canonizer3.canonizer.com/history/2604/2
https://canonizer3.canonizer.com/history/2602/2
https://canonizer3.canonizer.com/history/2590/1
There are several links where I'm having the same problems.

**Comment by array-junkie** [comment]
PR is raised: [#699](https://github.com/the-canonizer/canonizer-3.0-api/pull/699)

**Comment by sajid315** [comment]
> @sajid315 I am still facing the same issue for old camps reference links : https://canonizer3.canonizer.com/history/2608/1 https://canonizer3.canonizer.com/history/2604/2 https://canonizer3.canonizer.com/history/2602/2 https://canonizer3.canonizer.com/history/2590/1 There are several links where I'm having the same problems.

@rupalichavan9860 now the links are working fine that you mentioned above. Have a look please.

**Comment by rupalichavan9860** [comment]
Working fine now

**Comment by hassaanCD** [comment]
Working fine on live
